version: "2.1"
services:

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

  mongodb:
      image: mongo:latest
      container_name: mongodb
      restart: always
      environment:
          MONGO_INITDB_ROOT_USERNAME: xander
          MONGO_INITDB_ROOT_PASSWORD: oz13ecTe3YIbzsZiKWm7
          MONGO_INITDB_DATABASE: twitch
      ports:
          - 27017:27017
      volumes:
          - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  chat-bot:
    container_name: chat-bot
    build: ./ChatBot
    depends_on:
      rabbitmq:
        condition: service_healthy

  persistor:
    container_name: persistor
    build: ./Persistor
    depends_on:
      rabbitmq:
        condition: service_healthy

